version: "3.8"

services:
  app:
    container_name: rick-n-morty-ui
    image: rick-n-morty-ui2
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
